### ISSUE TITLE
Error during assets:install – AppNotFoundException for "SwagInsiderPreviews" after update from 6.7.0.1 to 6.7.1.0

### ISSUE THREAD

**Issue by cybercom684** [shopware/platform#11515]
### Shopware Version

6.7.0.1

### Affected area / extension

Platform(Default)

### Actual behaviour

while updating the Shop version, after migration:

```
Copying files for app: SwagInsiderPreviews
13:49:40 CRITICAL  [console] Error thrown while running command "assets:install". Message: "Could not find app with name "SwagInsiderPreviews"
[
  "exception" => Shopware\Core\Framework\App\Exception\AppNotFoundException {
    #message: "Could not find app with name "SwagInsiderPreviews""
    #code: 0
    #file: "/var/www/clients/client1/web12/web/vendor/shopware/core/Framework/App/AppException.php"
    #line: 98
    -statusCode: 404
    -headers: []
    #parameters: [
      "entity" => "app",
      "field" => "name",
      "value" => "SwagInsiderPreviews"
    ]
    #statusCode: 404
    #errorCode: "FRAMEWORK__APP_NOT_FOUND"
    trace: {
      /var/www/clients/client1/web12/web/vendor/shopware/core/Framework/App/AppException.php:98 { …}
      /var/www/clients/client1/web12/web/vendor/shopware/core/Framework/App/Source/SourceResolver.php:79 { …}
      /var/www/clients/client1/web12/web/vendor/shopware/core/Framework/Plugin/Util/AssetService.php:69 { …}
      /var/www/clients/client1/web12/web/vendor/shopware/core/Framework/Adapter/Asset/AssetInstallCommand.php:51 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/console/Command/Command.php:279 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:1094 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/framework-bundle/Console/Application.php:123 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:342 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/framework-bundle/Console/Application.php:77 { …}
      /var/www/clients/client1/web12/web/vendor/shopware/core/Maintenance/System/Command/SystemUpdateFinishCommand.php:157 { …}
      /var/www/clients/client1/web12/web/vendor/shopware/core/Maintenance/System/Command/SystemUpdateFinishCommand.php:147 { …}
      /var/www/clients/client1/web12/web/vendor/shopware/core/Maintenance/System/Command/SystemUpdateFinishCommand.php:103 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/console/Command/Command.php:279 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:1094 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/framework-bundle/Console/Application.php:123 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:342 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/framework-bundle/Console/Application.php:77 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:193 { …}
      /var/www/clients/client1/web12/web/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49 { …}
      /var/www/clients/client1/web12/web/vendor/autoload_runtime.php:29 { …}
      /var/www/clients/client1/web12/web/bin/console:17 {
        › 
        › require_once __DIR__ . '/../vendor/autoload_runtime.php';
        › 
        arguments: {
          "/var/www/clients/client1/web12/web/vendor/autoload_runtime.php"
        }
      }
    }
  },
  "command" => "assets:install",
  "message" => "Could not find app with name "SwagInsiderPreviews""
]
13:49:40 DEBUG     [console] Command "assets:install" exited with code "1"
[
  "command" => "assets:install",
  "code" => 1
]

In AppException.php line 98:
                                                                
  [Shopware\Core\Framework\App\Exception\AppNotFoundException]  
  Could not find app with name "SwagInsiderPreviews"            
                                                                

Exception trace:
  at /var/www/clients/client1/web12/web/vendor/shopware/core/Framework/App/AppException.php:98
 Shopware\Core\Framework\App\AppException::notFoundByField() at /var/www/clients/client1/web12/web/vendor/shopware/core/Framework/App/Source/SourceResolver.php:79
 Shopware\Core\Framework\App\Source\SourceResolver->filesystemForAppName() at /var/www/clients/client1/web12/web/vendor/shopware/core/Framework/Plugin/Util/AssetService.php:69
 Shopware\Core\Framework\Plugin\Util\AssetService->copyAssetsFromApp() at /var/www/clients/client1/web12/web/vendor/shopware/core/Framework/Adapter/Asset/AssetInstallCommand.php:51
 Shopware\Core\Framework\Adapter\Asset\AssetInstallCommand->execute() at /var/www/clients/client1/web12/web/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:1094
 Symfony\Component\Console\Application->doRunCommand() at /var/www/clients/client1/web12/web/vendor/symfony/framework-bundle/Console/Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:342
 Symfony\Component\Console\Application->doRun() at /var/www/clients/client1/web12/web/vendor/symfony/framework-bundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/clients/client1/web12/web/vendor/shopware/core/Maintenance/System/Command/SystemUpdateFinishCommand.php:157
 Shopware\Core\Maintenance\System\Command\SystemUpdateFinishCommand->runCommand() at /var/www/clients/client1/web12/web/vendor/shopware/core/Maintenance/System/Command/SystemUpdateFinishCommand.php:147
 Shopware\Core\Maintenance\System\Command\SystemUpdateFinishCommand->installAssets() at /var/www/clients/client1/web12/web/vendor/shopware/core/Maintenance/System/Command/SystemUpdateFinishCommand.php:103
 Shopware\Core\Maintenance\System\Command\SystemUpdateFinishCommand->execute() at /var/www/clients/client1/web12/web/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:1094
 Symfony\Component\Console\Application->doRunCommand() at /var/www/clients/client1/web12/web/vendor/symfony/framework-bundle/Console/Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:342
 Symfony\Component\Console\Application->doRun() at /var/www/clients/client1/web12/web/vendor/symfony/framework-bundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/clients/client1/web12/web/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->run() at /var/www/clients/client1/web12/web/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/clients/client1/web12/web/vendor/autoload_runtime.php:29
 require_once() at /var/www/clients/client1/web12/web/bin/console:17

assets:install [-f|--force]
```

### Expected behaviour

I have seen, another issue with the same plugin was sloved by set the plugin on active false in database

### How to reproduce

just update via notifications [language: German]

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

**Comment by frobel** [comment]
Addition to that:

Error just occurs with updates from 6.7.0.1 to 6.7.1.x

Updates from 6.6.x -> latest 6.7.1.x are working fine.

**Comment by UtechtDustin** [comment]
@keulinho is there an ETA for the Backport ?   
We can't update from 6.6.10.4 to the latest version, because of that issue.

**Comment by thomasru38** [comment]
I can confirm this bug updating from 6.6.10.4 -> 6.7.1.2

**Comment by keulinho** [comment]
That issue should have been solved with 6.7.1.2

Also before we could not reproduce the issue when we updated from 6.6.x 🤔 

Can you share how you executed the update? Over CLI or via admin? so we can reproduce the issue?

**Comment by thomasru38** [comment]
> That issue should have been solved with 6.7.1.2
> 
> Also before we could not reproduce the issue when we updated from 6.6.x 🤔
> 
> Can you share how you executed the update? Over CLI or via admin? so we can reproduce the issue?

Update via admin. All Plugins deactivated before updating, All Custom Themes unassigned from sales channels and deactivated. Running PHP 8.3 MariaDB 10.11.13 SwagInsiderPreviews can be found in DB table "app" and "app_translation" Is just removing these entries a possible solution? Thanks for your help really do appreciate it.

**Comment by UtechtDustin** [comment]
We also deactivated all plugins and custom themes (and unassigned it from the sales channel).   
PHP 8.3 with 10.11.13-MariaDB-0ubuntu0.24.04.1.   
Like @thomasru38 we also have the `SwagInsiderPreviews` app in the Database.   

It would be great if we could get an solution for that issue, we are not a fan or running outdated software.   
We always update shopware using the webinterface.

**Comment by keulinho** [comment]
Hey @thomasru38 & @UtechtDustin, 

you should be able to mark the `SwagInsiderPreviews` entry in app table as `active=0`, that should solve the issue. 

After the update to 6.7.1.x that app should be automatically removed, and that is actually the issue, the app is removed during the update, but some step in the upgrade process still thinks the app is there, but it isn't anymore. 

Can you share the exact error message and stack trace that you get?

**Comment by UtechtDustin** [comment]
After deactivating the app `SwagInsiderPreviews ` in the database  (`active=0`) i was able to update to `6.7.1.2`.
After the update, i was no longer able to access the admin webinterface, because of an 500er (`SERVICE_REGISTRY_URL` was missing). After manually clearing the cache it worked again.   

The app `SwagInsiderPreviews` still exists in the database.  
Should we delete it from the database manually ? (If yes, which entries?)

**Comment by keulinho** [comment]
You should be able to manually uninstall the app via `bin/console app:uninstall SwagInsiderPreviews`

**Comment by UtechtDustin** [comment]
Worked fine, thanks!
