### ISSUE TITLE
HTTP Cache Poisoning by removing or manipulating sw-states and sw-cache-hash cookies

### ISSUE THREAD

**Issue by rf-elio** [shopware/platform#12756]
### Shopware Version

*

### Affected area / extension

Platform(Default)

### Actual behaviour

A customer can poison the Shopware HTTP cache by removing the sw-states and sw-cache-hash cookies. For example, if a logged-in customer deletes these cookies and accesses a cacheable page, the page will be rendered using their current session data and then cached, since the cache cookies are missing.

This issue can occur due to:

- Different expiry times set for the session cookie and the sw-states/sw-cache-hash cookies
- Browser extensions that mistakenly identify these cookies as tracking cookies
- Attackers intentionally attempting to poison the HTTP cache

The HttpCacheKeyGenerator used by the Shopware\Core\Framework\Adapter\Cache\Http\CacheStore only relies on the users request which allows this behavoir.

### Expected behaviour

The user should not be able to poison the http cache by removing or manipulating the sw-states and sw-context-hash cookie. Shopware is setting the sw-states and sw-cache-hash cookie correctly in the response. The CacheStore should rely on the corrected cookies in the response and not on the user request.

### How to reproduce

**Pre Condition**

- Enable production mode: APP_ENV=prod
- Enable http cache: SHOPWARE_HTTP_CACHE_ENABLED=1

**Steps**
1. Login as a customer
2. Delete the cookies "sw-cache-hash" and "sw-states", but keep the session id cookie
3. Clear Shopware HTTP Cache
4. Open a product detail page (or any page that can be cached by the http cache)
5. Open the same page in another browser or incognito where no user is logged in

**Expected Result**
The page was cached by the logged in user due to the missing sw-states cookie. The cache key is the same as for not logged in user, because the sw-cache-hash cookie was removed. The not logged in user will now receive the result right from the http cache that was set by the logged in customer that warmed up the cache with before.

**Comment by keulinho** [comment]
Hey @rf-elio , 
thanks for creating the issue and helping identify the problem here. That could explain some cache.poisioning issue we could not reproduce so far. 

please take a look at the fix if that also solves your issue, the basic reproducer you added in you description is solved with that!

**Comment by DenKonElio** [comment]
@keulinho We reviewed your changes and if we saw it correctly, the first possible issue (Different expiry times set for the session cookie and the sw-states/sw-cache-hash cookies) was not fixed.

You could still get a corrupted cookie state, when the session cookie_lifetime differs from the expiry time within the sw-states/sw-cache-hash cookies.

The core needs a synchronisation between these two expiry times.

Can you please review this?
