### ISSUE TITLE
WebInstaller does not work for Subdirectory Installation if another Shopware 6 or any corrupt `composer.lock` file already exists in parent directory

### ISSUE THREAD

**Issue by jr-timme** [shopware/platform#3047]
### PHP Version

8.2

### Shopware Version

6.0+

### Expected behaviour

The new WebInstaller should be able to install a new Shopware 6 Instance in a subdirectory, even if there already exists a shopware installation in the parent directory

### Actual behaviour

If there already exists a Shopware 6, or any other Composer Project, installation in the parent directory the WebInstaller will instead overwrite/update the already existing installation

### How to reproduce

Set up a new Shopware 6 Installation with project Dir `/var/www/mywebsite.com/` and docroot `/var/www/mywebsite.com/public`

Then try to install another Shopware Installation with project Dir `/var/www/mywebsite.com/staging`  and document root `/var/www/mywebsite.com/staging/public` 

The WebInstaller will then pick `/var/www/mywebsite.com/staging`  as the `$project_dir` and check for a `composer.lock` inside `/var/www/mywebsite.com/`  which already exists and then proceed to update this installation instead.

A possible workaround would be something like:
```diff
diff --git a/src/WebInstaller/src/Services/RecoveryManager.php b/src/WebInstaller/src/Services/RecoveryManager.php
index 7b6feb6718..ade94f0f2f 100644
--- a/src/WebInstaller/src/Services/RecoveryManager.php
+++ b/src/WebInstaller/src/Services/RecoveryManager.php
@@ -41,11 +41,14 @@ class RecoveryManager
         $projectDir = $this->getProjectDir();
 
         $composerLookups = [
-            \dirname($projectDir) . '/composer.lock',
             $projectDir . '/composer.lock',
             $projectDir . '/shopware/composer.lock',
         ];
 
+       if ( basename($projectDir) == "public" ) {
+               $composerLookups[] = \dirname($projectDir) . '/composer.lock';
+       }
+
         foreach ($composerLookups as $composerLookup) {
             if (file_exists($composerLookup)) {
                 /** @var array{packages: array{name: string, version: string}[]} $composerJson */
```

As far as I can tell a user is not supposed to run the installer from inside the `public` directory, so I'm not sure if the check for the parent directory is necessary at all. And if the user is supposed to run the Installer from inside the `public` directory it should not create another `public` directory during installation.

Installing the second Shopware 6 instance inside the public directory is also not desirable as that would expose sensitive files to a regular user.

If I'm missing something please let me know, as installing Shopware into a subdirectory is a rather common use-case for us.

**Comment by keulinho** [comment]
Hey @jr-timme, thanks for raising the issue, 
isn't the root problem that the parent directory of the project dir takes precedence over the actual project dir?

Does this fix also solve your issue?

```diff
         $projectDir = $this->getProjectDir();
 
         $composerLookups = [
-            \dirname($projectDir) . '/composer.lock',
             $projectDir . '/composer.lock',
+           \dirname($projectDir) . '/composer.lock',
             $projectDir . '/shopware/composer.lock',
         ];

         foreach ($composerLookups as $composerLookup) {
             if (file_exists($composerLookup)) {
                 /** @var array{packages: array{name: string, version: string}[]} $composerJson */
```

**Comment by jr-timme** [comment]
The order alone sadly does not fix the issue.

During a new installation there is no `composer.lock` file inside `$projectDir` as that only gets created during the download/installation one step after the `/configure`

So the `foreach` still checks the parent directory for a `composer.lock`, finds it, and then assumes i want to update the existing installation instead of creating a new one.

Another potential "problem" with this is: If i create an empty `composer.lock` file in the parent directory the installer crashes with:
```php
Warning: Trying to access array offset on value of type null

    Exception Logs Stack Trace 

ErrorException
in Services/RecoveryManager.php (line 54)

            foreach ($composerLookups as $composerLookup) {
                if (file_exists($composerLookup)) {
                    /** @var array{packages: array{name: string, version: string}[]} $composerJson */
                    $composerJson = json_decode((string) file_get_contents($composerLookup), true, \JSON_THROW_ON_ERROR);
>                    foreach ($composerJson['packages'] as $package) {
                        if ($package['name'] === 'shopware/core' || $package['name'] === 'shopware/platform') {
                            return \dirname($composerLookup);
                        }
                    }
                }
```
Additional error handling for this edge-case would probably be nice, even if a "corrupt" `composer.lock` file is probably quite uncommon.

A `composer.lock` from another CMS/Shop System however seems to be fine as
```php
if ($package['name'] === 'shopware/core' || $package['name'] === 'shopware/platform') {
```
does not match and therefore this path gets ignored. I'll change the issue title again to reflect that.

**Comment by shyim** [comment]
My suggested patch would be:

```
$composerLookups = [
            $projectDir . '/composer.lock',
            \dirname($projectDir) . '/composer.lock',
        ];

        foreach ($composerLookups as $composerLookup) {
            if (file_exists($composerLookup)) {
                /** @var array{packages?: array{name: string, version: string}[]} $composerJson */
                try {
                    $composerJson = json_decode((string) file_get_contents($composerLookup), true, \JSON_THROW_ON_ERROR);
                } catch (\JsonException) {
                    continue;
                }

                if (!isset($composerJson['packages'])) {
                    continue;
                }

                foreach ($composerJson['packages'] as $package) {
                    if ($package['name'] === 'shopware/core' || $package['name'] === 'shopware/platform') {
                        return \dirname($composerLookup);
                    }
                }
            }
        }
```

I guess this should also solve your issue @jr-timme?

The intention was also to put the phar file into the public folder 😅

**Comment by jr-timme** [comment]
If I put the phar file into `/var/www/mywebsite.com/staging/` the problem still persists as `\dirname($projectDir) . '/composer.lock',` points to `/var/www/mywebsite.com/composer.lock` which already exists due to another shopware 6 installation inside the parent directory.

If I create the `public` directory, put the phar file inside it and set the docroot to it before installation the installer creates another `public` directory inside the first one which also seems wrong:
```bash
/var/www/mywebsite.com/staging # tree -L 2
.
└── public
    ├── bin
    ├── composer.json
    ├── composer.lock
    ├── config
    ├── custom
    ├── docker-compose.override.yml
    ├── docker-compose.yml
    ├── files
    ├── public
    ├── symfony.lock
    ├── var
    └── vendor

8 directories, 5 files
```

after the `phar` downloads everything i get a `No input file specified.`   because shopware now expects the docroot to be `/var/www/mywebsite.com/staging/public/public`

If the `phar` should already be copied inside the `public` directory it should download everything to it's parent directory.

A perhaps naive idea/fix for this could be:
```diff
diff --git a/src/WebInstaller/src/Controller/InstallController.php b/src/WebInstaller/src/Controller/InstallController.php
index 165cca4dd7..2bac81ce6b 100644
--- a/src/WebInstaller/src/Controller/InstallController.php
+++ b/src/WebInstaller/src/Controller/InstallController.php
@@ -43,7 +43,7 @@ class InstallController extends AbstractController
     public function run(Request $request): StreamedResponse
     {
         $shopwareVersion = $request->query->get('shopwareVersion', '');
-        $folder = $this->recoveryManager->getProjectDir();
+        $folder = \dirname($this->recoveryManager->getProjectDir());
 
         $fs = new Filesystem();
         $fs->copy(\dirname(__DIR__) . '/Resources/install-template/composer.json', $folder . '/composer.json');
@@ -86,7 +86,7 @@ class InstallController extends AbstractController
     #[Route('/install/_cleanup', name: 'install_cleanup', methods: ['POST'])]
     public function cleanup(): StreamedResponse
     {
-        $folder = $this->recoveryManager->getProjectDir();
+        $folder = \dirname($this->recoveryManager->getProjectDir());
 
         $fs = new Filesystem();
         $htaccessFile = $folder . '/public/.htaccess';
```

Of course the text: `After downloading you should switch your document root to the newly created folder public. ` and `Nach dem Herunterladen solltest Du das Dokumenten-Stammverzeichnis auf das neu erstellte Verzeichnis public ändern.` would also need to be changed to reflect this

**Comment by shyim** [comment]
The intention was to put the phar into the public folder as everything else should not be accessible through the web.

Maybe we should limit that to public folders?

**Comment by jr-timme** [comment]
Limiting everything to the public folder would also simplify the nginx configuration as there is no need for another location with a different docroot for just the phar and a user would not need to switch the docroot after installation.

Adding the two `/dirname` calls to the `InstallController.php` seems to do just that, however as I'm not too familiar with the rest of the code and did not extensively test it there might be problems with it or there exists a different better solution

**Comment by shyim** [comment]
Sounds good. Then let's only allow placing the phar into the public folder.

**Comment by jr-timme** [comment]
Is there any update on this issue? Seeing as 6.5 got released today and the only download option on the website is the new installer this could cause some major issues if someone wants to test things in a subdirectory staging environment.

**Comment by shyim** [comment]
It is now in QA will release it tomorrow :)

**Comment by shyim** [comment]
Fixed with https://github.com/shopware/platform/commit/2d4f2050ab9748d6620b394e2ab5d4560c2752c5

**Comment by jr-timme** [comment]
Sorry for the delay, I was just able to test the changes, and it looks like the fix does not work correctly. (tested with the latest 3 releases from https://github.com/shopware/web-installer/releases)

The installer still shows the notice `After downloading you should switch your document root to the newly created folder public.` and the files get downloaded to the current document root which means the new public directory is still `/var/www/mydomain.com/public/public` or `/var/www/mydomain.com/staging/public/public`. in case of a subdirectory.

If this is the desired behavior we can also work with that, we just need to know if we need to adapt our nginx configuration accordingly.

**Comment by shyim** [comment]
Hey,

For Updates it's fine to put the installer into the `public` directly and just execute it.
For New Installations, the folder where the file is will be used as root directory, so a new folder `public` will be created and the user should change the document root.

We don't want to write files into the parent directory as we don't know what there is.

If that does not work for you, it would be nice if we could get an test account to debug this

**Comment by jr-timme** [comment]
> We don't want to write files into the parent directory as we don't know what there is.

But isn't that exactly what you are doing in case of an update?

This is also the problem with Staging Environments in a subdirectory which I described in the first comment.
As long as the installer does not have to reside in the `public` directory, and it checks the parent directory during updates it will always pick up the already existing installation and update that instead of installing a new one.
(unless subdirectory installations are not something that is supported, but that would break quite a lot of setups as a subdirectory installation is often the only way to test stuff due to plugin licenses which are, iirc, bound to the fqdn)

I think checking if the current directory is named `public` and the parent directory contains only the `public` directory and nothing else would be the best solution here, that way updates, new installations and subdirectory installations can all work with a single web server configuration and there is no need to change the document root mid-installation.

The Contao Manager which, iirc, was the inspiration for this installer, does something similar and prints a warning if the parent directory contains anything except the `public` directory.

```
Installation directory not empty

The root directory of your future Contao installation is not empty, we have found 1 file(s) that might be overwritten by the installation process. It is recommended to create an empty directory structure for Contao, but you can also remove the following files and check again if you are sure they are unused.

 -   bar

[ ] I want to install Contao into the non-empty directory. I understand that this might overwrite any existing files on my webspace.
```


Setting up a test server would be no problem, I'm also willing to test any possible changes. Is there any way for me to contact you directly, so that we could exchange the necessary credentials?

**Comment by shyim** [comment]
Is the problem the installation or updating process? From context I assume updating. We added 3 weeks ago [realpath](https://github.com/shopware/platform/commit/3414f9905f522d9df4513da0ac3e66021fd5c8bc) that should already fix such issues.

For staging mostly the website layout is:

```
/shop (live)
/shop/staging/public (staging) (http://localhost/staging/public)
```

some people also do symlinking to get rid of public:
```
/shop (live)
/shop/staging/public => /somewhere/else/public (staging) (http://localhost/staging)
```

in both cases it should be fine to go one folder back (when the shopware-installer.phar.php is in public folder) to land in the Shopware Staging project. 🤔 


We can also setup a quick Zoom call, to clearify this and speed up :)

**Comment by jr-timme** [comment]
Currently, we have Problems both with installations and updates due to the difference of the directory in which the installer must reside. We really want to prevent having to change the nginx configuration mid-installation as that would lead confusion with the majority of our customers.

I would be more than happy to schedule a quick meeting, I've sent you a Mail to the address on your GitHub profile, if there is a better address feel free to use that to respond to it.
